# Image js
FROM node:18

# Directory
WORKDIR /app

# File configuration package
COPY package*.json ./

# Install dependences
RUN npm install

# Copy code 
COPY . .

# Expose port
EXPOSE 80

# Comand to initial server
CMD ["node", "server.js"]
